const blogContent = [
    { type: 'paragraph', value: '“Use people’s laziness and become rich.”' },
    { type: 'paragraph', value: 'If someone can capitalize on people’s laziness, they can become rich. By providing comfort and convenience, businesses can charge premium prices — and people are willing to pay. Swiggy and Zomato are prime examples of this business model.' },
    { type: 'paragraph', value: 'Hi everyone 👋! Last week, I visited Kerala, exploring Vagamon and Kochi. It was an experience filled with beautiful memories. During this trip, I visited the famous Lulu Mall. Ever since I was a child, I’ve been intrigued by the business strategies behind places and events, and Lulu Mall was no exception.' },
    { type: 'paragraph', value: 'We all know that for middle-class people, shopping at a mall may not always fit their budget. I realized this during my visit to Chennai’s Phoenix Market City Mall, and I had the same thoughts while visiting Lulu Mall.' },
    { type: 'heading', level: 2, value: '🔍 Interesting Business Insights I Observed at Lulu Mall' },
    { type: 'heading', level: 3, value: '1. Premium Enjoyment for Kids' },
    { type: 'paragraph', value: 'Lulu Mall’s indoor amusement area offers attractions like the Roller Coaster, Ferris Wheel, and Cine Coaster. It also features arcade games and VR experiences. I noticed many kids enjoying themselves here — it truly is an exciting place for them. However, these premium rides and games come at a high cost. While the enjoyment is top-notch, it’s clearly a premium experience designed to encourage spending.' },
    { type: 'image', src: 'https://cdn-images-1.medium.com/v2/resize:fit:1000/1*Fq4D6-wJXPL-6o9PBMNtRA.jpeg', alt: 'Lulu Mall Kids Amusement Area' }, 
    { type: 'heading', level: 3, value: '2. The Food Court Strategy' },
    { type: 'paragraph', value: 'On the third floor, Lulu Mall presents a diverse range of dining options. A subtle but clever observation I made was the pricing strategy: food outlets near the escalators charge higher prices due to increased foot traffic, while those located farther away offer comparatively lower rates. This model successfully capitalizes on customer behavior and convenience.' },
    { type: 'image', src: 'https://cdn-images-1.medium.com/v2/resize:fit:1000/1*EO7hC1neqJF3-SDRGj16Xg.jpeg', alt: 'Lulu Mall Food Court' },
    { type: 'heading', level: 3, value: '3. Strategic Store Placement' },
    { type: 'paragraph', value: 'The mall’s layout is meticulously designed with anchor stores like Lulu Hypermarket and PVR Cinemas placed at strategic locations. This encourages visitors to walk through the entire mall, exposing them to other shops along the way. It’s a smart way to boost foot traffic and create opportunities for impulse purchases, benefiting both large and small retailers.' },
    { type: 'heading', level: 3, value: '4. Seasonal Themes and Promotions' },
    { type: 'paragraph', value: 'To attract repeat visitors, Lulu Mall frequently adopts seasonal promotions and festive decorations. Events such as cultural festivals, sales, and themed displays keep the mall lively and engaging. This ensures that customers always have a reason to return.' },
    { type: 'heading', level: 3, value: '5. Focus on Luxury and Aspirational Brands' },
    { type: 'paragraph', value: 'Lulu Mall caters to a broad demographic by offering both essentials for middle-class families and high-end luxury brands. This balance attracts a wide customer base, including those looking to indulge occasionally in premium experiences. It’s a strategy that drives sales while maintaining the mall’s aspirational appeal.' },
    { type: 'heading', level: 3, value: '6. Catchy quotes help to keep the brand in customers’ minds.' },
    { type: 'paragraph', value: 'There are numerous examples of this. Each shop in the mall uses advertisements with a quote. These quotes are strategically placed in the mall by the shops.' },
    { type: 'image', src: 'https://cdn-images-1.medium.com/v2/resize:fit:1000/1*5kenXQOvJXU_LI-9EjtjdA.jpeg', alt: 'Lulu Mall Advertisements with Quotes' }, 
    { type: 'heading', level: 2, value: '❓ A Fun Question:' },
    { type: 'paragraph', value: 'I’ve yet to try burgers or pizza — what do they taste like? Can you compare them to South Indian dishes like Sambar Rice with Potato Fry, Rasam with Potato Fry, or Biryani? I’d love to hear your thoughts!' },
    { type: 'paragraph', value: 'Alright, guys, that’s it for this blog. Oh, and one more thing! Today, I’ve been on a blogging spree. If you have time, don’t forget to check out my latest post on “Emacs & Org Mode in Windows.”' },
    { type: 'paragraph', value: 'When you feel this content is valuable, follow me for more upcoming Blogs.' },
    { type: 'heading', level: 2, value: 'Connect with Me:' },
    { type: 'list', items: [
      '<strong>LinkedIn:</strong> Anand Sundaramoorthy',
      '<strong>Instagram:</strong> @anandsundaramoorthysa',
      '<strong>Email:</strong> sanand03072005@gmail.com',
    ]},
   ];
  
   export default blogContent;